export default {
	BridgeTalk: false,
	Infinity: false,
	NaN: false,
	app: false,
	alert: false,
	confirm: false,
	decodeURI: false,
	decodeURIComponent: false,
	encodeURI: false,
	encodeURIComponent: false,
	escape: false,
	eval: false,
	isFinite: false,
	isNaN: false,
	isXMLName: false,
	localize: false,
	parseFloat: false,
	parseInt: false,
	prompt: false,
	setDefaultXMLNamespace: false,
	unescape: false,
	uneval: false,
};
