export default {
	$: false,
	Object: false,
	Array: false,
	Math: false,
	Date: false,
	Function: false,
	String: false,
	Number: false,
	Boolean: false,
	RegExp: false,
	Error: false,
	File: false,
	Folder: false,
	Socket: false,
	ReflectionInfo: false,
	Reflection: false,
	QName: false,
	Namespace: false,
	XML: false,
	XMLList: false,
	UnitValue: false,
};
